SET FEEDBACK OFF

PROMPT
PROMPT ************************************************************
PROMPT
PROMPT -> CREATION DE LA BASE DE DONNEES << URBAN BASKET >>
PROMPT

DROP TABLE UTILISATEUR CASCADE CONSTRAINTS purge;
DROP TABLE SALLE CASCADE CONSTRAINTS purge;
DROP TABLE RESERVATION CASCADE CONSTRAINTS purge;

CREATE TABLE UTILISATEUR (
	Pseudo VARCHAR2(15),
	Mdp VARCHAR2(25) NOT NULL,
	Nom VARCHAR2(25) NOT NULL,
	Prenom VARCHAR2(25) NOT NULL,
	Date_naissance DATE NOT NULL,
	Mail VARCHAR2(125) NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY (Pseudo)
);

CREATE TABLE SALLE (
	Id INTEGER,
	Proprietaire VARCHAR2(40) NOT NULL,
	Nb_terrains INTEGER NOT NULL,
	Adresse VARCHAR2(80),
	Lattitude DECIMAL(10, 6 ) NOT NULL,
	Longitude DECIMAL(10, 6 ) NOT NULL,
	CONSTRAINT PK_SALLE PRIMARY KEY (Id)
);

CREATE TABLE RESERVATION (
	Id_salle INTEGER,
	Pseudo_user VARCHAR2(15),
	Date_resa DATE NOT NULL,
	Numero INTEGER NOT NULL,
	CONSTRAINT PK_RESA PRIMARY KEY (Id_salle,Pseudo_user),
	CONSTRAINT FK_ID_SALLE FOREIGN KEY (Id_salle) REFERENCES SALLE (Id) ON DELETE CASCADE,
	CONSTRAINT FK_PSEUDO_UTILISATEUR FOREIGN KEY (Pseudo_user) REFERENCES UTILISATEUR (Pseudo) ON DELETE CASCADE
);

PROMPT  ->  Tables creees

COMMIT;
PROMPT
PROMPT -> FIN DE CREATION
PROMPT

SET FEEDBACK ON
